### ISSUE TITLE
bug(init): provider names with a dot are not saved correctlty

### ISSUE THREAD

**Issue by dwmkerr** [dwmkerr/terminal-ai#78]
Using the name `openai-3.5` gives:

```
providers:
  openai-3:
    '5':
      name: openai-3.5
      type: openai
      baseURL: https://api.openai.com/v1/
      model: gpt-3.5-turbo
      apiKey: '123'
provider: openai-3.5
```

This is likely an error in the 'enrichProperty' code
